// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"io"
	"strings"
)

func PageStyles(page string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		loweredPage := strings.ToLower(page)
		href := "/static/pages/" + loweredPage + "/" + loweredPage + ".css"

		_, err := io.WriteString(
			w,
			`<link rel="stylesheet" href="`+href+`">`,
		)
		return err
	})
}

var _ = templruntime.GeneratedTemplate
